export const sampleData = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice@example.com',
    department: 'Engineering',
    amount: 85000,
    date: '2025-01-15',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Bob Smith',
    email: 'bob@example.com',
    department: 'Marketing',
    amount: 72000,
    date: '2025-02-20',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Carol Davis',
    email: 'carol@example.com',
    department: 'Sales',
    amount: 91000,
    date: '2025-03-10',
    status: 'On Leave',
  },
  {
    id: 4,
    name: 'Dan Wilson',
    email: 'dan@example.com',
    department: 'Engineering',
    amount: 78000,
    date: '2024-11-05',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Eva Martinez',
    email: 'eva@example.com',
    department: 'HR',
    amount: 68000,
    date: '2025-04-01',
    status: 'Active',
  },
];
